stages:
  - build
  - test
  - package
  - deploy

variables:
  APPLICATION_NAME: "my-dotnet"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet restore
    - dotnet build --configuration Release

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:5.0
  script:
    - dotnet test

package:
  stage: package
  image: mcr.microsoft.com/dotnet/sdk:5.0
  before_script:
    - apt-get update && apt-get install -y zip
  script:
    - dotnet publish --configuration Release --output ./publish
    - cd publish
    - zip -r ../app.zip .

deploy:
  stage: deploy
  image: amazon/aws-cli:2.x
  before_script:
    - apt-get update && apt-get install -y unzip
  script:
    - aws s3 cp app.zip s3://$S3_BUCKET/$APPLICATION_NAME/app.zip
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
